ai_provider: gemini_relay
auto_resume: true
batch_size: 5
distance: null
enable_ai_pre_filter: true
enable_pre_filter: false
exclude_title_keywords: []
experience_level:
- 1
- 2
- 3
- 4
filter_german_jobs: true
gemini_api_key: ''
gemini_model: gemini-2.5-flash
geo_id: null
german_title_keywords:
- entwickler
- ingenieur
- leiter
- berater
- mitarbeiter
- werkstudent
- praktikant
- oftwareentwickler
headless: false
list_only: false
llm_delay: 1.0
locations:
- Germany
- Switzerland
max_experience_years: 10
max_pages: 50
min_experience_years: 1
openai_api_key: sk-koCHFMu3wv7IKg4frBgacDU471l1BaOYWgtNPsIUNSxrVgjn
openai_base_url: https://api.vectorengine.ai/v1
openai_model: gemini-2.5-flash
output_filename:
- out.csv
output_filtered_csv: /Users/amy/Desktop/LinkedIn-Easy-Apply-Bot/project/job-bot/LinkedIn-Collect-main/out/jobs_filtered_out.csv
output_json: /Users/amy/Desktop/LinkedIn-Easy-Apply-Bot/project/job-bot/LinkedIn-Collect-main/out/jobs_passed.json
output_passed_csv: /Users/amy/Desktop/LinkedIn-Easy-Apply-Bot/project/job-bot/LinkedIn-Collect-main/out/jobs_passed.csv
pages_before_detail: 5
positions:
- Frontend Developer
- React
- React Native
- TypeScript
- Full Stack Engineer
- Software Engineer
- Web Developer
rate: 25
resume_path: ./resume.json
salary: 60000
sort_by: DD
start_page: 0
time_filter: r604800
uploads:
  Cover Letter: ./cover_letter.pdf
  Resume: ./resume.pdf
use_llm_scoring: true
